# Generated by Django 3.0.7 on 2020-07-01 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_profiel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profiel',
            new_name='Profile',
        ),
    ]
