# Generated by Django 3.0.7 on 2020-07-01 10:19

import User.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20200701_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='facebook.jpg', upload_to=User.models.upload_location),
        ),
    ]
