# Generated by Django 3.0.7 on 2020-07-01 10:57

import User.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_auto_20200701_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default=User.models.image, upload_to=User.models.upload_location),
        ),
    ]
