# Generated by Django 3.0.7 on 2020-07-01 11:19

import User.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_auto_20200701_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default=User.models.set_avatar, upload_to=User.models.upload_location),
        ),
    ]
