# Generated by Django 3.0.7 on 2020-07-05 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test', to='Product.Room'),
        ),
    ]
