# Generated by Django 3.0.7 on 2020-07-07 09:57

import Product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_auto_20200706_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=Product.models.upload_location),
        ),
    ]
