# Generated by Django 3.0.7 on 2020-07-08 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0007_bookings_is_booked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='is_booked',
        ),
    ]
